// Generated by https://quicktype.io

export interface PokeTypeList {
  count: number;
  next: string;
  previous: string;
  results: basicListPoke[];
}

export interface basicListPoke {
  name: string;
  url: string;
}
